# Generated by Django 2.1.2 on 2018-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('category_id', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'category_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=11, null=True)),
                ('purchase_price', models.CharField(blank=True, max_length=11, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=30, null=True)),
                ('images_num', models.IntegerField(blank=True, null=True)),
                ('search_key', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=11, null=True)),
                ('shop_ids', models.TextField(blank=True, null=True)),
                ('cat_ids', models.CharField(blank=True, max_length=200, null=True)),
                ('special_price', models.CharField(blank=True, max_length=11, null=True)),
                ('special_price_start', models.CharField(blank=True, max_length=32, null=True)),
                ('special_price_end', models.CharField(blank=True, max_length=32, null=True)),
                ('total_sell', models.IntegerField()),
                ('create_at', models.CharField(blank=True, max_length=30, null=True)),
                ('quality_date', models.CharField(blank=True, max_length=30, null=True)),
                ('show_index', models.IntegerField(blank=True, null=True)),
                ('buy_limit', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('create_at', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'product_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('order_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductTierPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('tier_price', models.CharField(blank=True, max_length=30, null=True)),
                ('tier_count', models.IntegerField(blank=True, null=True)),
                ('customer_group_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'product_tier_price',
                'managed': False,
            },
        ),
    ]
