# Generated by Django 2.1.2 on 2018-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_type', models.IntegerField(blank=True, null=True)),
                ('coupon_code', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('need_price', models.IntegerField(blank=True, null=True)),
                ('coupon_price', models.IntegerField(blank=True, null=True)),
                ('coupon_desc', models.CharField(blank=True, max_length=50, null=True)),
                ('isuse', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('first_name', models.CharField(blank=True, max_length=32, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('email', models.CharField(blank=True, max_length=32, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('default_address_id', models.IntegerField(blank=True, null=True)),
                ('password_hash', models.CharField(blank=True, max_length=90, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=30, null=True)),
                ('company', models.CharField(blank=True, max_length=20, null=True)),
                ('street', models.CharField(blank=True, max_length=200, null=True)),
                ('post_code', models.CharField(blank=True, max_length=11, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'customer_address',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('coupon_id', models.IntegerField(blank=True, null=True)),
                ('is_used', models.IntegerField(blank=True, null=True)),
                ('is_expire', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_coupon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerInviter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter_id', models.IntegerField(blank=True, null=True)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('is_coupon', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'customer_inviter',
                'managed': False,
            },
        ),
    ]
