# Generated by Django 2.1.2 on 2018-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_area', models.TextField(blank=True, null=True)),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('driver_time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('tax_total', models.CharField(blank=True, max_length=20, null=True)),
                ('invoice_total', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Refunds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, null=True)),
                ('pay_type', models.IntegerField(blank=True, null=True)),
                ('snap_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('new_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('refund', models.IntegerField(blank=True, null=True)),
                ('refund_products', models.CharField(blank=True, max_length=200, null=True)),
                ('refund_shipping', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'refunds',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_value', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tax',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(blank=True, max_length=50, null=True)),
                ('area_id', models.IntegerField(blank=True, null=True)),
                ('free_shipping', models.IntegerField(blank=True, null=True)),
                ('shipping_amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zipcode',
                'managed': False,
            },
        ),
    ]
