# Generated by Django 2.1.2 on 2018-11-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adminuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('boss', models.IntegerField(blank=True, null=True)),
                ('driver', models.IntegerField(blank=True, null=True)),
                ('store_manager', models.IntegerField()),
                ('sale_manager', models.IntegerField(blank=True, null=True)),
                ('sale_manager7', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adminuser',
                'managed': False,
            },
        ),
    ]
